name: formatting_check
run-name: Check code formatting
on: [push, pull_request]
jobs:
  formatting_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paolorechia/pox@v1.0.1
      - uses: actionshub/markdownlint@main
        with:
          tox_env: "format_check"